/** \file
 *  This C header file was generated by $ANTLR version 3.3 Nov 30, 2010 12:45:30
 *
 *     -  From the grammar source file : YSmart.g
 *     -                            On : 2016-05-22 00:58:35
 *     -                 for the lexer : YSmartLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer YSmartLexer has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pYSmartLexer, which is returned from a call to YSmartLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 * * The methods in pYSmartLexer are  as follows:
 *
 *  -  void      pYSmartLexer->T_RESERVED(pYSmartLexer)
 *  -  void      pYSmartLexer->T_ALIAS(pYSmartLexer)
 *  -  void      pYSmartLexer->T_TABLE_NAME(pYSmartLexer)
 *  -  void      pYSmartLexer->T_WITH(pYSmartLexer)
 *  -  void      pYSmartLexer->T_SELECT(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COLUMN_LIST(pYSmartLexer)
 *  -  void      pYSmartLexer->T_SELECT_COLUMN(pYSmartLexer)
 *  -  void      pYSmartLexer->T_FROM(pYSmartLexer)
 *  -  void      pYSmartLexer->T_SELECTED_TABLE(pYSmartLexer)
 *  -  void      pYSmartLexer->T_WHERE(pYSmartLexer)
 *  -  void      pYSmartLexer->T_HIERARCHICAL(pYSmartLexer)
 *  -  void      pYSmartLexer->T_GROUP_BY(pYSmartLexer)
 *  -  void      pYSmartLexer->T_HAVING(pYSmartLexer)
 *  -  void      pYSmartLexer->T_MODEL(pYSmartLexer)
 *  -  void      pYSmartLexer->T_UNION(pYSmartLexer)
 *  -  void      pYSmartLexer->T_ORDER_BY_CLAUSE(pYSmartLexer)
 *  -  void      pYSmartLexer->T_FOR_UPDATE_CLAUSE(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_OR(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_AND(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_NOT(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_exists(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_is(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_comparison(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_group_comparison(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_in(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_is_a_set(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_is_any(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_is_empty(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_is_of_type(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_is_present(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_like(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_memeber(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_between(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_regexp_like(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_submultiset(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_equals_path(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_under_path(pYSmartLexer)
 *  -  void      pYSmartLexer->T_COND_paren(pYSmartLexer)
 *  -  void      pYSmartLexer->T__88(pYSmartLexer)
 *  -  void      pYSmartLexer->T__89(pYSmartLexer)
 *  -  void      pYSmartLexer->T__90(pYSmartLexer)
 *  -  void      pYSmartLexer->T__91(pYSmartLexer)
 *  -  void      pYSmartLexer->T__92(pYSmartLexer)
 *  -  void      pYSmartLexer->T__93(pYSmartLexer)
 *  -  void      pYSmartLexer->T__94(pYSmartLexer)
 *  -  void      pYSmartLexer->T__95(pYSmartLexer)
 *  -  void      pYSmartLexer->T__96(pYSmartLexer)
 *  -  void      pYSmartLexer->T__97(pYSmartLexer)
 *  -  void      pYSmartLexer->T__98(pYSmartLexer)
 *  -  void      pYSmartLexer->T__99(pYSmartLexer)
 *  -  void      pYSmartLexer->T__100(pYSmartLexer)
 *  -  void      pYSmartLexer->T__101(pYSmartLexer)
 *  -  void      pYSmartLexer->T__102(pYSmartLexer)
 *  -  void      pYSmartLexer->T__103(pYSmartLexer)
 *  -  void      pYSmartLexer->T__104(pYSmartLexer)
 *  -  void      pYSmartLexer->T__105(pYSmartLexer)
 *  -  void      pYSmartLexer->T__106(pYSmartLexer)
 *  -  void      pYSmartLexer->T__107(pYSmartLexer)
 *  -  void      pYSmartLexer->T__108(pYSmartLexer)
 *  -  void      pYSmartLexer->T__109(pYSmartLexer)
 *  -  void      pYSmartLexer->T__110(pYSmartLexer)
 *  -  void      pYSmartLexer->T__111(pYSmartLexer)
 *  -  void      pYSmartLexer->T__112(pYSmartLexer)
 *  -  void      pYSmartLexer->T__113(pYSmartLexer)
 *  -  void      pYSmartLexer->T__114(pYSmartLexer)
 *  -  void      pYSmartLexer->T__115(pYSmartLexer)
 *  -  void      pYSmartLexer->T__116(pYSmartLexer)
 *  -  void      pYSmartLexer->T__117(pYSmartLexer)
 *  -  void      pYSmartLexer->T__118(pYSmartLexer)
 *  -  void      pYSmartLexer->T__119(pYSmartLexer)
 *  -  void      pYSmartLexer->T__120(pYSmartLexer)
 *  -  void      pYSmartLexer->T__121(pYSmartLexer)
 *  -  void      pYSmartLexer->T__122(pYSmartLexer)
 *  -  void      pYSmartLexer->T__123(pYSmartLexer)
 *  -  void      pYSmartLexer->T__124(pYSmartLexer)
 *  -  void      pYSmartLexer->T__125(pYSmartLexer)
 *  -  void      pYSmartLexer->T__126(pYSmartLexer)
 *  -  void      pYSmartLexer->T__127(pYSmartLexer)
 *  -  void      pYSmartLexer->T__128(pYSmartLexer)
 *  -  void      pYSmartLexer->T__129(pYSmartLexer)
 *  -  void      pYSmartLexer->T__130(pYSmartLexer)
 *  -  void      pYSmartLexer->T__131(pYSmartLexer)
 *  -  void      pYSmartLexer->T__132(pYSmartLexer)
 *  -  void      pYSmartLexer->T__133(pYSmartLexer)
 *  -  void      pYSmartLexer->T__134(pYSmartLexer)
 *  -  void      pYSmartLexer->T__135(pYSmartLexer)
 *  -  void      pYSmartLexer->T__136(pYSmartLexer)
 *  -  void      pYSmartLexer->T__137(pYSmartLexer)
 *  -  void      pYSmartLexer->T__138(pYSmartLexer)
 *  -  void      pYSmartLexer->T__139(pYSmartLexer)
 *  -  void      pYSmartLexer->T__140(pYSmartLexer)
 *  -  void      pYSmartLexer->T__141(pYSmartLexer)
 *  -  void      pYSmartLexer->T__142(pYSmartLexer)
 *  -  void      pYSmartLexer->T__143(pYSmartLexer)
 *  -  void      pYSmartLexer->T__144(pYSmartLexer)
 *  -  void      pYSmartLexer->T__145(pYSmartLexer)
 *  -  void      pYSmartLexer->T__146(pYSmartLexer)
 *  -  void      pYSmartLexer->T__147(pYSmartLexer)
 *  -  void      pYSmartLexer->T__148(pYSmartLexer)
 *  -  void      pYSmartLexer->T__149(pYSmartLexer)
 *  -  void      pYSmartLexer->T__150(pYSmartLexer)
 *  -  void      pYSmartLexer->T__151(pYSmartLexer)
 *  -  void      pYSmartLexer->T__152(pYSmartLexer)
 *  -  void      pYSmartLexer->T__153(pYSmartLexer)
 *  -  void      pYSmartLexer->T__154(pYSmartLexer)
 *  -  void      pYSmartLexer->T__155(pYSmartLexer)
 *  -  void      pYSmartLexer->T__156(pYSmartLexer)
 *  -  void      pYSmartLexer->T__157(pYSmartLexer)
 *  -  void      pYSmartLexer->T__158(pYSmartLexer)
 *  -  void      pYSmartLexer->T__159(pYSmartLexer)
 *  -  void      pYSmartLexer->T__160(pYSmartLexer)
 *  -  void      pYSmartLexer->T__161(pYSmartLexer)
 *  -  void      pYSmartLexer->T__162(pYSmartLexer)
 *  -  void      pYSmartLexer->T__163(pYSmartLexer)
 *  -  void      pYSmartLexer->T__164(pYSmartLexer)
 *  -  void      pYSmartLexer->T__165(pYSmartLexer)
 *  -  void      pYSmartLexer->T__166(pYSmartLexer)
 *  -  void      pYSmartLexer->T__167(pYSmartLexer)
 *  -  void      pYSmartLexer->T__168(pYSmartLexer)
 *  -  void      pYSmartLexer->T__169(pYSmartLexer)
 *  -  void      pYSmartLexer->T__170(pYSmartLexer)
 *  -  void      pYSmartLexer->T__171(pYSmartLexer)
 *  -  void      pYSmartLexer->T__172(pYSmartLexer)
 *  -  void      pYSmartLexer->T__173(pYSmartLexer)
 *  -  void      pYSmartLexer->T__174(pYSmartLexer)
 *  -  void      pYSmartLexer->T__175(pYSmartLexer)
 *  -  void      pYSmartLexer->T__176(pYSmartLexer)
 *  -  void      pYSmartLexer->T__177(pYSmartLexer)
 *  -  void      pYSmartLexer->T__178(pYSmartLexer)
 *  -  void      pYSmartLexer->T__179(pYSmartLexer)
 *  -  void      pYSmartLexer->T__180(pYSmartLexer)
 *  -  void      pYSmartLexer->T__181(pYSmartLexer)
 *  -  void      pYSmartLexer->T__182(pYSmartLexer)
 *  -  void      pYSmartLexer->T__183(pYSmartLexer)
 *  -  void      pYSmartLexer->T__184(pYSmartLexer)
 *  -  void      pYSmartLexer->T__185(pYSmartLexer)
 *  -  void      pYSmartLexer->T__186(pYSmartLexer)
 *  -  void      pYSmartLexer->T__187(pYSmartLexer)
 *  -  void      pYSmartLexer->T__188(pYSmartLexer)
 *  -  void      pYSmartLexer->T__189(pYSmartLexer)
 *  -  void      pYSmartLexer->T__190(pYSmartLexer)
 *  -  void      pYSmartLexer->T__191(pYSmartLexer)
 *  -  void      pYSmartLexer->T__192(pYSmartLexer)
 *  -  void      pYSmartLexer->T__193(pYSmartLexer)
 *  -  void      pYSmartLexer->T__194(pYSmartLexer)
 *  -  void      pYSmartLexer->T__195(pYSmartLexer)
 *  -  void      pYSmartLexer->T__196(pYSmartLexer)
 *  -  void      pYSmartLexer->T__197(pYSmartLexer)
 *  -  void      pYSmartLexer->T__198(pYSmartLexer)
 *  -  void      pYSmartLexer->T__199(pYSmartLexer)
 *  -  void      pYSmartLexer->T__200(pYSmartLexer)
 *  -  void      pYSmartLexer->T__201(pYSmartLexer)
 *  -  void      pYSmartLexer->T__202(pYSmartLexer)
 *  -  void      pYSmartLexer->T__203(pYSmartLexer)
 *  -  void      pYSmartLexer->T__204(pYSmartLexer)
 *  -  void      pYSmartLexer->T__205(pYSmartLexer)
 *  -  void      pYSmartLexer->T__206(pYSmartLexer)
 *  -  void      pYSmartLexer->T__207(pYSmartLexer)
 *  -  void      pYSmartLexer->T__208(pYSmartLexer)
 *  -  void      pYSmartLexer->T__209(pYSmartLexer)
 *  -  void      pYSmartLexer->T__210(pYSmartLexer)
 *  -  void      pYSmartLexer->T__211(pYSmartLexer)
 *  -  void      pYSmartLexer->T__212(pYSmartLexer)
 *  -  void      pYSmartLexer->T__213(pYSmartLexer)
 *  -  void      pYSmartLexer->T__214(pYSmartLexer)
 *  -  void      pYSmartLexer->T__215(pYSmartLexer)
 *  -  void      pYSmartLexer->T__216(pYSmartLexer)
 *  -  void      pYSmartLexer->T__217(pYSmartLexer)
 *  -  void      pYSmartLexer->T__218(pYSmartLexer)
 *  -  void      pYSmartLexer->T__219(pYSmartLexer)
 *  -  void      pYSmartLexer->T__220(pYSmartLexer)
 *  -  void      pYSmartLexer->T__221(pYSmartLexer)
 *  -  void      pYSmartLexer->T__222(pYSmartLexer)
 *  -  void      pYSmartLexer->T__223(pYSmartLexer)
 *  -  void      pYSmartLexer->T__224(pYSmartLexer)
 *  -  void      pYSmartLexer->T__225(pYSmartLexer)
 *  -  void      pYSmartLexer->T__226(pYSmartLexer)
 *  -  void      pYSmartLexer->T__227(pYSmartLexer)
 *  -  void      pYSmartLexer->T__228(pYSmartLexer)
 *  -  void      pYSmartLexer->T__229(pYSmartLexer)
 *  -  void      pYSmartLexer->T__230(pYSmartLexer)
 *  -  void      pYSmartLexer->T__231(pYSmartLexer)
 *  -  void      pYSmartLexer->T__232(pYSmartLexer)
 *  -  void      pYSmartLexer->T__233(pYSmartLexer)
 *  -  void      pYSmartLexer->T__234(pYSmartLexer)
 *  -  void      pYSmartLexer->T__235(pYSmartLexer)
 *  -  void      pYSmartLexer->T__236(pYSmartLexer)
 *  -  void      pYSmartLexer->T__237(pYSmartLexer)
 *  -  void      pYSmartLexer->T__238(pYSmartLexer)
 *  -  void      pYSmartLexer->T__239(pYSmartLexer)
 *  -  void      pYSmartLexer->T__240(pYSmartLexer)
 *  -  void      pYSmartLexer->T__241(pYSmartLexer)
 *  -  void      pYSmartLexer->T__242(pYSmartLexer)
 *  -  void      pYSmartLexer->T__243(pYSmartLexer)
 *  -  void      pYSmartLexer->T__244(pYSmartLexer)
 *  -  void      pYSmartLexer->T__245(pYSmartLexer)
 *  -  void      pYSmartLexer->T__246(pYSmartLexer)
 *  -  void      pYSmartLexer->T__247(pYSmartLexer)
 *  -  void      pYSmartLexer->T__248(pYSmartLexer)
 *  -  void      pYSmartLexer->T__249(pYSmartLexer)
 *  -  void      pYSmartLexer->T__250(pYSmartLexer)
 *  -  void      pYSmartLexer->T__251(pYSmartLexer)
 *  -  void      pYSmartLexer->T__252(pYSmartLexer)
 *  -  void      pYSmartLexer->T__253(pYSmartLexer)
 *  -  void      pYSmartLexer->T__254(pYSmartLexer)
 *  -  void      pYSmartLexer->T__255(pYSmartLexer)
 *  -  void      pYSmartLexer->T__256(pYSmartLexer)
 *  -  void      pYSmartLexer->T__257(pYSmartLexer)
 *  -  void      pYSmartLexer->T__258(pYSmartLexer)
 *  -  void      pYSmartLexer->T__259(pYSmartLexer)
 *  -  void      pYSmartLexer->T__260(pYSmartLexer)
 *  -  void      pYSmartLexer->T__261(pYSmartLexer)
 *  -  void      pYSmartLexer->T__262(pYSmartLexer)
 *  -  void      pYSmartLexer->T__263(pYSmartLexer)
 *  -  void      pYSmartLexer->T__264(pYSmartLexer)
 *  -  void      pYSmartLexer->T__265(pYSmartLexer)
 *  -  void      pYSmartLexer->T__266(pYSmartLexer)
 *  -  void      pYSmartLexer->T__267(pYSmartLexer)
 *  -  void      pYSmartLexer->T__268(pYSmartLexer)
 *  -  void      pYSmartLexer->T__269(pYSmartLexer)
 *  -  void      pYSmartLexer->T__270(pYSmartLexer)
 *  -  void      pYSmartLexer->T__271(pYSmartLexer)
 *  -  void      pYSmartLexer->T__272(pYSmartLexer)
 *  -  void      pYSmartLexer->T__273(pYSmartLexer)
 *  -  void      pYSmartLexer->T__274(pYSmartLexer)
 *  -  void      pYSmartLexer->T__275(pYSmartLexer)
 *  -  void      pYSmartLexer->T__276(pYSmartLexer)
 *  -  void      pYSmartLexer->T__277(pYSmartLexer)
 *  -  void      pYSmartLexer->T__278(pYSmartLexer)
 *  -  void      pYSmartLexer->T__279(pYSmartLexer)
 *  -  void      pYSmartLexer->T__280(pYSmartLexer)
 *  -  void      pYSmartLexer->T__281(pYSmartLexer)
 *  -  void      pYSmartLexer->T__282(pYSmartLexer)
 *  -  void      pYSmartLexer->T__283(pYSmartLexer)
 *  -  void      pYSmartLexer->T__284(pYSmartLexer)
 *  -  void      pYSmartLexer->T__285(pYSmartLexer)
 *  -  void      pYSmartLexer->T__286(pYSmartLexer)
 *  -  void      pYSmartLexer->T__287(pYSmartLexer)
 *  -  void      pYSmartLexer->T__288(pYSmartLexer)
 *  -  void      pYSmartLexer->T__289(pYSmartLexer)
 *  -  void      pYSmartLexer->T__290(pYSmartLexer)
 *  -  void      pYSmartLexer->T__291(pYSmartLexer)
 *  -  void      pYSmartLexer->T__292(pYSmartLexer)
 *  -  void      pYSmartLexer->T__293(pYSmartLexer)
 *  -  void      pYSmartLexer->T__294(pYSmartLexer)
 *  -  void      pYSmartLexer->T__295(pYSmartLexer)
 *  -  void      pYSmartLexer->T__296(pYSmartLexer)
 *  -  void      pYSmartLexer->T__297(pYSmartLexer)
 *  -  void      pYSmartLexer->T__298(pYSmartLexer)
 *  -  void      pYSmartLexer->T__299(pYSmartLexer)
 *  -  void      pYSmartLexer->T__300(pYSmartLexer)
 *  -  void      pYSmartLexer->T__301(pYSmartLexer)
 *  -  void      pYSmartLexer->T__302(pYSmartLexer)
 *  -  void      pYSmartLexer->T__303(pYSmartLexer)
 *  -  void      pYSmartLexer->T__304(pYSmartLexer)
 *  -  void      pYSmartLexer->T__305(pYSmartLexer)
 *  -  void      pYSmartLexer->T__306(pYSmartLexer)
 *  -  void      pYSmartLexer->T__307(pYSmartLexer)
 *  -  void      pYSmartLexer->T__308(pYSmartLexer)
 *  -  void      pYSmartLexer->T__309(pYSmartLexer)
 *  -  void      pYSmartLexer->T__310(pYSmartLexer)
 *  -  void      pYSmartLexer->T__311(pYSmartLexer)
 *  -  void      pYSmartLexer->T__312(pYSmartLexer)
 *  -  void      pYSmartLexer->T__313(pYSmartLexer)
 *  -  void      pYSmartLexer->T__314(pYSmartLexer)
 *  -  void      pYSmartLexer->T__315(pYSmartLexer)
 *  -  void      pYSmartLexer->T__316(pYSmartLexer)
 *  -  void      pYSmartLexer->T__317(pYSmartLexer)
 *  -  void      pYSmartLexer->T__318(pYSmartLexer)
 *  -  void      pYSmartLexer->T__319(pYSmartLexer)
 *  -  void      pYSmartLexer->T__320(pYSmartLexer)
 *  -  void      pYSmartLexer->T__321(pYSmartLexer)
 *  -  void      pYSmartLexer->T__322(pYSmartLexer)
 *  -  void      pYSmartLexer->T__323(pYSmartLexer)
 *  -  void      pYSmartLexer->T__324(pYSmartLexer)
 *  -  void      pYSmartLexer->T__325(pYSmartLexer)
 *  -  void      pYSmartLexer->T__326(pYSmartLexer)
 *  -  void      pYSmartLexer->T__327(pYSmartLexer)
 *  -  void      pYSmartLexer->T__328(pYSmartLexer)
 *  -  void      pYSmartLexer->T__329(pYSmartLexer)
 *  -  void      pYSmartLexer->T__330(pYSmartLexer)
 *  -  void      pYSmartLexer->T__331(pYSmartLexer)
 *  -  void      pYSmartLexer->T__332(pYSmartLexer)
 *  -  void      pYSmartLexer->T__333(pYSmartLexer)
 *  -  void      pYSmartLexer->T__334(pYSmartLexer)
 *  -  void      pYSmartLexer->T__335(pYSmartLexer)
 *  -  void      pYSmartLexer->T__336(pYSmartLexer)
 *  -  void      pYSmartLexer->T__337(pYSmartLexer)
 *  -  void      pYSmartLexer->T__338(pYSmartLexer)
 *  -  void      pYSmartLexer->T__339(pYSmartLexer)
 *  -  void      pYSmartLexer->T__340(pYSmartLexer)
 *  -  void      pYSmartLexer->T__341(pYSmartLexer)
 *  -  void      pYSmartLexer->T__342(pYSmartLexer)
 *  -  void      pYSmartLexer->T__343(pYSmartLexer)
 *  -  void      pYSmartLexer->T__344(pYSmartLexer)
 *  -  void      pYSmartLexer->T__345(pYSmartLexer)
 *  -  void      pYSmartLexer->T__346(pYSmartLexer)
 *  -  void      pYSmartLexer->T__347(pYSmartLexer)
 *  -  void      pYSmartLexer->T__348(pYSmartLexer)
 *  -  void      pYSmartLexer->T__349(pYSmartLexer)
 *  -  void      pYSmartLexer->T__350(pYSmartLexer)
 *  -  void      pYSmartLexer->T__351(pYSmartLexer)
 *  -  void      pYSmartLexer->T__352(pYSmartLexer)
 *  -  void      pYSmartLexer->T__353(pYSmartLexer)
 *  -  void      pYSmartLexer->T__354(pYSmartLexer)
 *  -  void      pYSmartLexer->T__355(pYSmartLexer)
 *  -  void      pYSmartLexer->T__356(pYSmartLexer)
 *  -  void      pYSmartLexer->T__357(pYSmartLexer)
 *  -  void      pYSmartLexer->T__358(pYSmartLexer)
 *  -  void      pYSmartLexer->T__359(pYSmartLexer)
 *  -  void      pYSmartLexer->T__360(pYSmartLexer)
 *  -  void      pYSmartLexer->T__361(pYSmartLexer)
 *  -  void      pYSmartLexer->T__362(pYSmartLexer)
 *  -  void      pYSmartLexer->T__363(pYSmartLexer)
 *  -  void      pYSmartLexer->T__364(pYSmartLexer)
 *  -  void      pYSmartLexer->T__365(pYSmartLexer)
 *  -  void      pYSmartLexer->T__366(pYSmartLexer)
 *  -  void      pYSmartLexer->T__367(pYSmartLexer)
 *  -  void      pYSmartLexer->T__368(pYSmartLexer)
 *  -  void      pYSmartLexer->T__369(pYSmartLexer)
 *  -  void      pYSmartLexer->T__370(pYSmartLexer)
 *  -  void      pYSmartLexer->T__371(pYSmartLexer)
 *  -  void      pYSmartLexer->T__372(pYSmartLexer)
 *  -  void      pYSmartLexer->T__373(pYSmartLexer)
 *  -  void      pYSmartLexer->T__374(pYSmartLexer)
 *  -  void      pYSmartLexer->T__375(pYSmartLexer)
 *  -  void      pYSmartLexer->T__376(pYSmartLexer)
 *  -  void      pYSmartLexer->T__377(pYSmartLexer)
 *  -  void      pYSmartLexer->T__378(pYSmartLexer)
 *  -  void      pYSmartLexer->T__379(pYSmartLexer)
 *  -  void      pYSmartLexer->T__380(pYSmartLexer)
 *  -  void      pYSmartLexer->T__381(pYSmartLexer)
 *  -  void      pYSmartLexer->T__382(pYSmartLexer)
 *  -  void      pYSmartLexer->T__383(pYSmartLexer)
 *  -  void      pYSmartLexer->T__384(pYSmartLexer)
 *  -  void      pYSmartLexer->T__385(pYSmartLexer)
 *  -  void      pYSmartLexer->T__386(pYSmartLexer)
 *  -  void      pYSmartLexer->T__387(pYSmartLexer)
 *  -  void      pYSmartLexer->T__388(pYSmartLexer)
 *  -  void      pYSmartLexer->T__389(pYSmartLexer)
 *  -  void      pYSmartLexer->T__390(pYSmartLexer)
 *  -  void      pYSmartLexer->T__391(pYSmartLexer)
 *  -  void      pYSmartLexer->T__392(pYSmartLexer)
 *  -  void      pYSmartLexer->T__393(pYSmartLexer)
 *  -  void      pYSmartLexer->T__394(pYSmartLexer)
 *  -  void      pYSmartLexer->T__395(pYSmartLexer)
 *  -  void      pYSmartLexer->T__396(pYSmartLexer)
 *  -  void      pYSmartLexer->T__397(pYSmartLexer)
 *  -  void      pYSmartLexer->T__398(pYSmartLexer)
 *  -  void      pYSmartLexer->T__399(pYSmartLexer)
 *  -  void      pYSmartLexer->T__400(pYSmartLexer)
 *  -  void      pYSmartLexer->T__401(pYSmartLexer)
 *  -  void      pYSmartLexer->T__402(pYSmartLexer)
 *  -  void      pYSmartLexer->T__403(pYSmartLexer)
 *  -  void      pYSmartLexer->T__404(pYSmartLexer)
 *  -  void      pYSmartLexer->T__405(pYSmartLexer)
 *  -  void      pYSmartLexer->T__406(pYSmartLexer)
 *  -  void      pYSmartLexer->T__407(pYSmartLexer)
 *  -  void      pYSmartLexer->T__408(pYSmartLexer)
 *  -  void      pYSmartLexer->T__409(pYSmartLexer)
 *  -  void      pYSmartLexer->T__410(pYSmartLexer)
 *  -  void      pYSmartLexer->T__411(pYSmartLexer)
 *  -  void      pYSmartLexer->T__412(pYSmartLexer)
 *  -  void      pYSmartLexer->T__413(pYSmartLexer)
 *  -  void      pYSmartLexer->T__414(pYSmartLexer)
 *  -  void      pYSmartLexer->T__415(pYSmartLexer)
 *  -  void      pYSmartLexer->T__416(pYSmartLexer)
 *  -  void      pYSmartLexer->T__417(pYSmartLexer)
 *  -  void      pYSmartLexer->T__418(pYSmartLexer)
 *  -  void      pYSmartLexer->T__419(pYSmartLexer)
 *  -  void      pYSmartLexer->T__420(pYSmartLexer)
 *  -  void      pYSmartLexer->T__421(pYSmartLexer)
 *  -  void      pYSmartLexer->T__422(pYSmartLexer)
 *  -  void      pYSmartLexer->T__423(pYSmartLexer)
 *  -  void      pYSmartLexer->T__424(pYSmartLexer)
 *  -  void      pYSmartLexer->T__425(pYSmartLexer)
 *  -  void      pYSmartLexer->T__426(pYSmartLexer)
 *  -  void      pYSmartLexer->T__427(pYSmartLexer)
 *  -  void      pYSmartLexer->T__428(pYSmartLexer)
 *  -  void      pYSmartLexer->T__429(pYSmartLexer)
 *  -  void      pYSmartLexer->T__430(pYSmartLexer)
 *  -  void      pYSmartLexer->T__431(pYSmartLexer)
 *  -  void      pYSmartLexer->T__432(pYSmartLexer)
 *  -  void      pYSmartLexer->T__433(pYSmartLexer)
 *  -  void      pYSmartLexer->T__434(pYSmartLexer)
 *  -  void      pYSmartLexer->T__435(pYSmartLexer)
 *  -  void      pYSmartLexer->T__436(pYSmartLexer)
 *  -  void      pYSmartLexer->T__437(pYSmartLexer)
 *  -  void      pYSmartLexer->T__438(pYSmartLexer)
 *  -  void      pYSmartLexer->T__439(pYSmartLexer)
 *  -  void      pYSmartLexer->T__440(pYSmartLexer)
 *  -  void      pYSmartLexer->T__441(pYSmartLexer)
 *  -  void      pYSmartLexer->T__442(pYSmartLexer)
 *  -  void      pYSmartLexer->T__443(pYSmartLexer)
 *  -  void      pYSmartLexer->T__444(pYSmartLexer)
 *  -  void      pYSmartLexer->T__445(pYSmartLexer)
 *  -  void      pYSmartLexer->T__446(pYSmartLexer)
 *  -  void      pYSmartLexer->T__447(pYSmartLexer)
 *  -  void      pYSmartLexer->T__448(pYSmartLexer)
 *  -  void      pYSmartLexer->T__449(pYSmartLexer)
 *  -  void      pYSmartLexer->T__450(pYSmartLexer)
 *  -  void      pYSmartLexer->T__451(pYSmartLexer)
 *  -  void      pYSmartLexer->T__452(pYSmartLexer)
 *  -  void      pYSmartLexer->T__453(pYSmartLexer)
 *  -  void      pYSmartLexer->T__454(pYSmartLexer)
 *  -  void      pYSmartLexer->T__455(pYSmartLexer)
 *  -  void      pYSmartLexer->T__456(pYSmartLexer)
 *  -  void      pYSmartLexer->T__457(pYSmartLexer)
 *  -  void      pYSmartLexer->T__458(pYSmartLexer)
 *  -  void      pYSmartLexer->T__459(pYSmartLexer)
 *  -  void      pYSmartLexer->T__460(pYSmartLexer)
 *  -  void      pYSmartLexer->T__461(pYSmartLexer)
 *  -  void      pYSmartLexer->T__462(pYSmartLexer)
 *  -  void      pYSmartLexer->T__463(pYSmartLexer)
 *  -  void      pYSmartLexer->T__464(pYSmartLexer)
 *  -  void      pYSmartLexer->T__465(pYSmartLexer)
 *  -  void      pYSmartLexer->T__466(pYSmartLexer)
 *  -  void      pYSmartLexer->T__467(pYSmartLexer)
 *  -  void      pYSmartLexer->T__468(pYSmartLexer)
 *  -  void      pYSmartLexer->T__469(pYSmartLexer)
 *  -  void      pYSmartLexer->T__470(pYSmartLexer)
 *  -  void      pYSmartLexer->T__471(pYSmartLexer)
 *  -  void      pYSmartLexer->T__472(pYSmartLexer)
 *  -  void      pYSmartLexer->T__473(pYSmartLexer)
 *  -  void      pYSmartLexer->T__474(pYSmartLexer)
 *  -  void      pYSmartLexer->T__475(pYSmartLexer)
 *  -  void      pYSmartLexer->T__476(pYSmartLexer)
 *  -  void      pYSmartLexer->T__477(pYSmartLexer)
 *  -  void      pYSmartLexer->T__478(pYSmartLexer)
 *  -  void      pYSmartLexer->T__479(pYSmartLexer)
 *  -  void      pYSmartLexer->T__480(pYSmartLexer)
 *  -  void      pYSmartLexer->T__481(pYSmartLexer)
 *  -  void      pYSmartLexer->T__482(pYSmartLexer)
 *  -  void      pYSmartLexer->T__483(pYSmartLexer)
 *  -  void      pYSmartLexer->T__484(pYSmartLexer)
 *  -  void      pYSmartLexer->T__485(pYSmartLexer)
 *  -  void      pYSmartLexer->T__486(pYSmartLexer)
 *  -  void      pYSmartLexer->T__487(pYSmartLexer)
 *  -  void      pYSmartLexer->T__488(pYSmartLexer)
 *  -  void      pYSmartLexer->T__489(pYSmartLexer)
 *  -  void      pYSmartLexer->T__490(pYSmartLexer)
 *  -  void      pYSmartLexer->T__491(pYSmartLexer)
 *  -  void      pYSmartLexer->T__492(pYSmartLexer)
 *  -  void      pYSmartLexer->T__493(pYSmartLexer)
 *  -  void      pYSmartLexer->T__494(pYSmartLexer)
 *  -  void      pYSmartLexer->T__495(pYSmartLexer)
 *  -  void      pYSmartLexer->T__496(pYSmartLexer)
 *  -  void      pYSmartLexer->T__497(pYSmartLexer)
 *  -  void      pYSmartLexer->T__498(pYSmartLexer)
 *  -  void      pYSmartLexer->T__499(pYSmartLexer)
 *  -  void      pYSmartLexer->T__500(pYSmartLexer)
 *  -  void      pYSmartLexer->T__501(pYSmartLexer)
 *  -  void      pYSmartLexer->T__502(pYSmartLexer)
 *  -  void      pYSmartLexer->T__503(pYSmartLexer)
 *  -  void      pYSmartLexer->T__504(pYSmartLexer)
 *  -  void      pYSmartLexer->T__505(pYSmartLexer)
 *  -  void      pYSmartLexer->T__506(pYSmartLexer)
 *  -  void      pYSmartLexer->T__507(pYSmartLexer)
 *  -  void      pYSmartLexer->T__508(pYSmartLexer)
 *  -  void      pYSmartLexer->T__509(pYSmartLexer)
 *  -  void      pYSmartLexer->T__510(pYSmartLexer)
 *  -  void      pYSmartLexer->T__511(pYSmartLexer)
 *  -  void      pYSmartLexer->T__512(pYSmartLexer)
 *  -  void      pYSmartLexer->T__513(pYSmartLexer)
 *  -  void      pYSmartLexer->T__514(pYSmartLexer)
 *  -  void      pYSmartLexer->T__515(pYSmartLexer)
 *  -  void      pYSmartLexer->T__516(pYSmartLexer)
 *  -  void      pYSmartLexer->T__517(pYSmartLexer)
 *  -  void      pYSmartLexer->T__518(pYSmartLexer)
 *  -  void      pYSmartLexer->T__519(pYSmartLexer)
 *  -  void      pYSmartLexer->T__520(pYSmartLexer)
 *  -  void      pYSmartLexer->T__521(pYSmartLexer)
 *  -  void      pYSmartLexer->T__522(pYSmartLexer)
 *  -  void      pYSmartLexer->T__523(pYSmartLexer)
 *  -  void      pYSmartLexer->T__524(pYSmartLexer)
 *  -  void      pYSmartLexer->T__525(pYSmartLexer)
 *  -  void      pYSmartLexer->T__526(pYSmartLexer)
 *  -  void      pYSmartLexer->T__527(pYSmartLexer)
 *  -  void      pYSmartLexer->T__528(pYSmartLexer)
 *  -  void      pYSmartLexer->T__529(pYSmartLexer)
 *  -  void      pYSmartLexer->T__530(pYSmartLexer)
 *  -  void      pYSmartLexer->QUOTED_STRING(pYSmartLexer)
 *  -  void      pYSmartLexer->ID(pYSmartLexer)
 *  -  void      pYSmartLexer->SEMI(pYSmartLexer)
 *  -  void      pYSmartLexer->COLON(pYSmartLexer)
 *  -  void      pYSmartLexer->DOUBLEDOT(pYSmartLexer)
 *  -  void      pYSmartLexer->DOT(pYSmartLexer)
 *  -  void      pYSmartLexer->POINT(pYSmartLexer)
 *  -  void      pYSmartLexer->COMMA(pYSmartLexer)
 *  -  void      pYSmartLexer->EXPONENT(pYSmartLexer)
 *  -  void      pYSmartLexer->ASTERISK(pYSmartLexer)
 *  -  void      pYSmartLexer->AT_SIGN(pYSmartLexer)
 *  -  void      pYSmartLexer->RPAREN(pYSmartLexer)
 *  -  void      pYSmartLexer->LPAREN(pYSmartLexer)
 *  -  void      pYSmartLexer->RBRACK(pYSmartLexer)
 *  -  void      pYSmartLexer->LBRACK(pYSmartLexer)
 *  -  void      pYSmartLexer->PLUS(pYSmartLexer)
 *  -  void      pYSmartLexer->MINUS(pYSmartLexer)
 *  -  void      pYSmartLexer->DIVIDE(pYSmartLexer)
 *  -  void      pYSmartLexer->EQ(pYSmartLexer)
 *  -  void      pYSmartLexer->PERCENTAGE(pYSmartLexer)
 *  -  void      pYSmartLexer->LLABEL(pYSmartLexer)
 *  -  void      pYSmartLexer->RLABEL(pYSmartLexer)
 *  -  void      pYSmartLexer->ASSIGN(pYSmartLexer)
 *  -  void      pYSmartLexer->ARROW(pYSmartLexer)
 *  -  void      pYSmartLexer->VERTBAR(pYSmartLexer)
 *  -  void      pYSmartLexer->DOUBLEVERTBAR(pYSmartLexer)
 *  -  void      pYSmartLexer->NOT_EQ(pYSmartLexer)
 *  -  void      pYSmartLexer->LTH(pYSmartLexer)
 *  -  void      pYSmartLexer->LEQ(pYSmartLexer)
 *  -  void      pYSmartLexer->GTH(pYSmartLexer)
 *  -  void      pYSmartLexer->GEQ(pYSmartLexer)
 *  -  void      pYSmartLexer->NUMBER(pYSmartLexer)
 *  -  void      pYSmartLexer->NUM(pYSmartLexer)
 *  -  void      pYSmartLexer->QUOTE(pYSmartLexer)
 *  -  void      pYSmartLexer->DOUBLEQUOTED_STRING(pYSmartLexer)
 *  -  void      pYSmartLexer->WS(pYSmartLexer)
 *  -  void      pYSmartLexer->SL_COMMENT(pYSmartLexer)
 *  -  void      pYSmartLexer->ML_COMMENT(pYSmartLexer)
 *  -  void      pYSmartLexer->TYPE_ATTR(pYSmartLexer)
 *  -  void      pYSmartLexer->ROWTYPE_ATTR(pYSmartLexer)
 *  -  void      pYSmartLexer->NOTFOUND_ATTR(pYSmartLexer)
 *  -  void      pYSmartLexer->FOUND_ATTR(pYSmartLexer)
 *  -  void      pYSmartLexer->ISOPEN_ATTR(pYSmartLexer)
 *  -  void      pYSmartLexer->ROWCOUNT_ATTR(pYSmartLexer)
 *  -  void      pYSmartLexer->BULK_ROWCOUNT_ATTR(pYSmartLexer)
 *  -  void      pYSmartLexer->CHARSET_ATTR(pYSmartLexer)
 *  -  void      pYSmartLexer->Tokens(pYSmartLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_YSmartLexer_H
#define _YSmartLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */
 
#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct YSmartLexer_Ctx_struct YSmartLexer, * pYSmartLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule 
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/* ========================
 * BACKTRACKING IS ENABLED
 * ========================
 */

/** Context tracking structure for YSmartLexer
 */
struct YSmartLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;


     void (*mT_RESERVED)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_ALIAS)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_TABLE_NAME)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_WITH)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_SELECT)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COLUMN_LIST)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_SELECT_COLUMN)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_FROM)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_SELECTED_TABLE)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_WHERE)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_HIERARCHICAL)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_GROUP_BY)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_HAVING)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_MODEL)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_UNION)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_ORDER_BY_CLAUSE)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_FOR_UPDATE_CLAUSE)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_OR)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_AND)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_NOT)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_exists)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_is)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_comparison)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_group_comparison)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_in)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_is_a_set)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_is_any)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_is_empty)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_is_of_type)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_is_present)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_like)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_memeber)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_between)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_regexp_like)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_submultiset)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_equals_path)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_under_path)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT_COND_paren)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__88)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__89)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__90)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__91)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__92)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__93)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__94)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__95)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__96)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__97)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__98)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__99)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__100)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__101)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__102)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__103)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__104)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__105)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__106)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__107)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__108)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__109)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__110)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__111)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__112)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__113)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__114)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__115)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__116)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__117)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__118)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__119)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__120)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__121)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__122)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__123)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__124)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__125)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__126)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__127)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__128)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__129)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__130)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__131)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__132)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__133)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__134)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__135)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__136)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__137)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__138)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__139)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__140)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__141)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__142)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__143)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__144)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__145)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__146)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__147)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__148)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__149)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__150)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__151)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__152)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__153)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__154)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__155)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__156)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__157)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__158)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__159)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__160)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__161)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__162)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__163)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__164)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__165)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__166)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__167)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__168)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__169)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__170)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__171)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__172)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__173)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__174)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__175)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__176)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__177)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__178)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__179)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__180)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__181)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__182)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__183)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__184)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__185)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__186)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__187)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__188)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__189)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__190)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__191)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__192)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__193)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__194)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__195)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__196)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__197)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__198)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__199)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__200)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__201)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__202)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__203)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__204)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__205)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__206)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__207)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__208)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__209)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__210)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__211)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__212)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__213)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__214)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__215)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__216)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__217)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__218)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__219)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__220)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__221)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__222)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__223)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__224)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__225)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__226)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__227)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__228)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__229)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__230)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__231)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__232)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__233)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__234)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__235)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__236)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__237)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__238)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__239)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__240)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__241)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__242)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__243)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__244)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__245)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__246)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__247)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__248)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__249)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__250)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__251)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__252)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__253)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__254)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__255)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__256)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__257)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__258)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__259)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__260)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__261)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__262)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__263)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__264)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__265)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__266)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__267)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__268)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__269)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__270)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__271)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__272)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__273)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__274)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__275)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__276)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__277)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__278)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__279)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__280)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__281)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__282)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__283)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__284)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__285)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__286)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__287)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__288)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__289)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__290)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__291)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__292)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__293)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__294)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__295)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__296)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__297)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__298)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__299)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__300)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__301)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__302)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__303)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__304)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__305)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__306)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__307)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__308)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__309)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__310)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__311)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__312)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__313)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__314)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__315)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__316)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__317)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__318)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__319)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__320)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__321)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__322)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__323)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__324)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__325)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__326)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__327)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__328)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__329)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__330)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__331)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__332)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__333)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__334)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__335)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__336)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__337)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__338)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__339)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__340)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__341)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__342)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__343)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__344)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__345)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__346)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__347)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__348)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__349)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__350)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__351)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__352)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__353)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__354)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__355)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__356)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__357)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__358)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__359)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__360)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__361)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__362)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__363)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__364)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__365)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__366)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__367)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__368)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__369)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__370)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__371)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__372)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__373)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__374)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__375)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__376)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__377)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__378)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__379)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__380)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__381)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__382)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__383)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__384)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__385)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__386)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__387)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__388)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__389)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__390)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__391)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__392)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__393)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__394)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__395)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__396)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__397)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__398)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__399)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__400)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__401)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__402)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__403)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__404)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__405)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__406)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__407)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__408)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__409)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__410)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__411)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__412)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__413)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__414)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__415)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__416)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__417)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__418)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__419)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__420)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__421)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__422)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__423)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__424)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__425)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__426)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__427)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__428)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__429)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__430)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__431)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__432)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__433)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__434)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__435)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__436)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__437)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__438)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__439)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__440)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__441)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__442)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__443)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__444)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__445)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__446)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__447)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__448)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__449)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__450)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__451)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__452)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__453)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__454)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__455)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__456)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__457)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__458)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__459)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__460)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__461)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__462)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__463)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__464)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__465)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__466)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__467)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__468)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__469)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__470)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__471)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__472)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__473)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__474)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__475)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__476)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__477)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__478)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__479)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__480)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__481)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__482)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__483)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__484)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__485)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__486)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__487)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__488)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__489)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__490)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__491)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__492)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__493)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__494)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__495)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__496)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__497)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__498)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__499)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__500)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__501)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__502)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__503)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__504)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__505)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__506)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__507)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__508)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__509)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__510)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__511)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__512)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__513)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__514)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__515)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__516)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__517)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__518)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__519)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__520)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__521)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__522)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__523)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__524)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__525)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__526)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__527)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__528)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__529)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mT__530)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mQUOTED_STRING)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mID)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mSEMI)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mCOLON)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mDOUBLEDOT)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mDOT)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mPOINT)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mCOMMA)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mEXPONENT)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mASTERISK)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mAT_SIGN)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mRPAREN)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mLPAREN)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mRBRACK)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mLBRACK)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mPLUS)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mMINUS)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mDIVIDE)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mEQ)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mPERCENTAGE)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mLLABEL)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mRLABEL)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mASSIGN)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mARROW)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mVERTBAR)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mDOUBLEVERTBAR)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mNOT_EQ)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mLTH)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mLEQ)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mGTH)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mGEQ)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mNUMBER)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mNUM)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mQUOTE)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mDOUBLEQUOTED_STRING)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mWS)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mSL_COMMENT)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mML_COMMENT)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mTYPE_ATTR)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mROWTYPE_ATTR)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mNOTFOUND_ATTR)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mFOUND_ATTR)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mISOPEN_ATTR)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mROWCOUNT_ATTR)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mBULK_ROWCOUNT_ATTR)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mCHARSET_ATTR)	(struct YSmartLexer_Ctx_struct * ctx);
     void (*mTokens)	(struct YSmartLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct YSmartLexer_Ctx_struct * ctx);
    void	    (*free)   (struct YSmartLexer_Ctx_struct * ctx);
        
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pYSmartLexer YSmartLexerNew         (pANTLR3_INPUT_STREAM instream);
ANTLR3_API pYSmartLexer YSmartLexerNewSSD      (pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the lexer will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define EOF      -1
#define T__88      88
#define T__89      89
#define T__90      90
#define T__91      91
#define T__92      92
#define T__93      93
#define T__94      94
#define T__95      95
#define T__96      96
#define T__97      97
#define T__98      98
#define T__99      99
#define T__100      100
#define T__101      101
#define T__102      102
#define T__103      103
#define T__104      104
#define T__105      105
#define T__106      106
#define T__107      107
#define T__108      108
#define T__109      109
#define T__110      110
#define T__111      111
#define T__112      112
#define T__113      113
#define T__114      114
#define T__115      115
#define T__116      116
#define T__117      117
#define T__118      118
#define T__119      119
#define T__120      120
#define T__121      121
#define T__122      122
#define T__123      123
#define T__124      124
#define T__125      125
#define T__126      126
#define T__127      127
#define T__128      128
#define T__129      129
#define T__130      130
#define T__131      131
#define T__132      132
#define T__133      133
#define T__134      134
#define T__135      135
#define T__136      136
#define T__137      137
#define T__138      138
#define T__139      139
#define T__140      140
#define T__141      141
#define T__142      142
#define T__143      143
#define T__144      144
#define T__145      145
#define T__146      146
#define T__147      147
#define T__148      148
#define T__149      149
#define T__150      150
#define T__151      151
#define T__152      152
#define T__153      153
#define T__154      154
#define T__155      155
#define T__156      156
#define T__157      157
#define T__158      158
#define T__159      159
#define T__160      160
#define T__161      161
#define T__162      162
#define T__163      163
#define T__164      164
#define T__165      165
#define T__166      166
#define T__167      167
#define T__168      168
#define T__169      169
#define T__170      170
#define T__171      171
#define T__172      172
#define T__173      173
#define T__174      174
#define T__175      175
#define T__176      176
#define T__177      177
#define T__178      178
#define T__179      179
#define T__180      180
#define T__181      181
#define T__182      182
#define T__183      183
#define T__184      184
#define T__185      185
#define T__186      186
#define T__187      187
#define T__188      188
#define T__189      189
#define T__190      190
#define T__191      191
#define T__192      192
#define T__193      193
#define T__194      194
#define T__195      195
#define T__196      196
#define T__197      197
#define T__198      198
#define T__199      199
#define T__200      200
#define T__201      201
#define T__202      202
#define T__203      203
#define T__204      204
#define T__205      205
#define T__206      206
#define T__207      207
#define T__208      208
#define T__209      209
#define T__210      210
#define T__211      211
#define T__212      212
#define T__213      213
#define T__214      214
#define T__215      215
#define T__216      216
#define T__217      217
#define T__218      218
#define T__219      219
#define T__220      220
#define T__221      221
#define T__222      222
#define T__223      223
#define T__224      224
#define T__225      225
#define T__226      226
#define T__227      227
#define T__228      228
#define T__229      229
#define T__230      230
#define T__231      231
#define T__232      232
#define T__233      233
#define T__234      234
#define T__235      235
#define T__236      236
#define T__237      237
#define T__238      238
#define T__239      239
#define T__240      240
#define T__241      241
#define T__242      242
#define T__243      243
#define T__244      244
#define T__245      245
#define T__246      246
#define T__247      247
#define T__248      248
#define T__249      249
#define T__250      250
#define T__251      251
#define T__252      252
#define T__253      253
#define T__254      254
#define T__255      255
#define T__256      256
#define T__257      257
#define T__258      258
#define T__259      259
#define T__260      260
#define T__261      261
#define T__262      262
#define T__263      263
#define T__264      264
#define T__265      265
#define T__266      266
#define T__267      267
#define T__268      268
#define T__269      269
#define T__270      270
#define T__271      271
#define T__272      272
#define T__273      273
#define T__274      274
#define T__275      275
#define T__276      276
#define T__277      277
#define T__278      278
#define T__279      279
#define T__280      280
#define T__281      281
#define T__282      282
#define T__283      283
#define T__284      284
#define T__285      285
#define T__286      286
#define T__287      287
#define T__288      288
#define T__289      289
#define T__290      290
#define T__291      291
#define T__292      292
#define T__293      293
#define T__294      294
#define T__295      295
#define T__296      296
#define T__297      297
#define T__298      298
#define T__299      299
#define T__300      300
#define T__301      301
#define T__302      302
#define T__303      303
#define T__304      304
#define T__305      305
#define T__306      306
#define T__307      307
#define T__308      308
#define T__309      309
#define T__310      310
#define T__311      311
#define T__312      312
#define T__313      313
#define T__314      314
#define T__315      315
#define T__316      316
#define T__317      317
#define T__318      318
#define T__319      319
#define T__320      320
#define T__321      321
#define T__322      322
#define T__323      323
#define T__324      324
#define T__325      325
#define T__326      326
#define T__327      327
#define T__328      328
#define T__329      329
#define T__330      330
#define T__331      331
#define T__332      332
#define T__333      333
#define T__334      334
#define T__335      335
#define T__336      336
#define T__337      337
#define T__338      338
#define T__339      339
#define T__340      340
#define T__341      341
#define T__342      342
#define T__343      343
#define T__344      344
#define T__345      345
#define T__346      346
#define T__347      347
#define T__348      348
#define T__349      349
#define T__350      350
#define T__351      351
#define T__352      352
#define T__353      353
#define T__354      354
#define T__355      355
#define T__356      356
#define T__357      357
#define T__358      358
#define T__359      359
#define T__360      360
#define T__361      361
#define T__362      362
#define T__363      363
#define T__364      364
#define T__365      365
#define T__366      366
#define T__367      367
#define T__368      368
#define T__369      369
#define T__370      370
#define T__371      371
#define T__372      372
#define T__373      373
#define T__374      374
#define T__375      375
#define T__376      376
#define T__377      377
#define T__378      378
#define T__379      379
#define T__380      380
#define T__381      381
#define T__382      382
#define T__383      383
#define T__384      384
#define T__385      385
#define T__386      386
#define T__387      387
#define T__388      388
#define T__389      389
#define T__390      390
#define T__391      391
#define T__392      392
#define T__393      393
#define T__394      394
#define T__395      395
#define T__396      396
#define T__397      397
#define T__398      398
#define T__399      399
#define T__400      400
#define T__401      401
#define T__402      402
#define T__403      403
#define T__404      404
#define T__405      405
#define T__406      406
#define T__407      407
#define T__408      408
#define T__409      409
#define T__410      410
#define T__411      411
#define T__412      412
#define T__413      413
#define T__414      414
#define T__415      415
#define T__416      416
#define T__417      417
#define T__418      418
#define T__419      419
#define T__420      420
#define T__421      421
#define T__422      422
#define T__423      423
#define T__424      424
#define T__425      425
#define T__426      426
#define T__427      427
#define T__428      428
#define T__429      429
#define T__430      430
#define T__431      431
#define T__432      432
#define T__433      433
#define T__434      434
#define T__435      435
#define T__436      436
#define T__437      437
#define T__438      438
#define T__439      439
#define T__440      440
#define T__441      441
#define T__442      442
#define T__443      443
#define T__444      444
#define T__445      445
#define T__446      446
#define T__447      447
#define T__448      448
#define T__449      449
#define T__450      450
#define T__451      451
#define T__452      452
#define T__453      453
#define T__454      454
#define T__455      455
#define T__456      456
#define T__457      457
#define T__458      458
#define T__459      459
#define T__460      460
#define T__461      461
#define T__462      462
#define T__463      463
#define T__464      464
#define T__465      465
#define T__466      466
#define T__467      467
#define T__468      468
#define T__469      469
#define T__470      470
#define T__471      471
#define T__472      472
#define T__473      473
#define T__474      474
#define T__475      475
#define T__476      476
#define T__477      477
#define T__478      478
#define T__479      479
#define T__480      480
#define T__481      481
#define T__482      482
#define T__483      483
#define T__484      484
#define T__485      485
#define T__486      486
#define T__487      487
#define T__488      488
#define T__489      489
#define T__490      490
#define T__491      491
#define T__492      492
#define T__493      493
#define T__494      494
#define T__495      495
#define T__496      496
#define T__497      497
#define T__498      498
#define T__499      499
#define T__500      500
#define T__501      501
#define T__502      502
#define T__503      503
#define T__504      504
#define T__505      505
#define T__506      506
#define T__507      507
#define T__508      508
#define T__509      509
#define T__510      510
#define T__511      511
#define T__512      512
#define T__513      513
#define T__514      514
#define T__515      515
#define T__516      516
#define T__517      517
#define T__518      518
#define T__519      519
#define T__520      520
#define T__521      521
#define T__522      522
#define T__523      523
#define T__524      524
#define T__525      525
#define T__526      526
#define T__527      527
#define T__528      528
#define T__529      529
#define T__530      530
#define T_RESERVED      4
#define T_ALIAS      5
#define T_TABLE_NAME      6
#define T_WITH      7
#define T_SELECT      8
#define T_COLUMN_LIST      9
#define T_SELECT_COLUMN      10
#define T_FROM      11
#define T_SELECTED_TABLE      12
#define T_WHERE      13
#define T_HIERARCHICAL      14
#define T_GROUP_BY      15
#define T_HAVING      16
#define T_MODEL      17
#define T_UNION      18
#define T_ORDER_BY_CLAUSE      19
#define T_FOR_UPDATE_CLAUSE      20
#define T_COND_OR      21
#define T_COND_AND      22
#define T_COND_NOT      23
#define T_COND_exists      24
#define T_COND_is      25
#define T_COND_comparison      26
#define T_COND_group_comparison      27
#define T_COND_in      28
#define T_COND_is_a_set      29
#define T_COND_is_any      30
#define T_COND_is_empty      31
#define T_COND_is_of_type      32
#define T_COND_is_present      33
#define T_COND_like      34
#define T_COND_memeber      35
#define T_COND_between      36
#define T_COND_regexp_like      37
#define T_COND_submultiset      38
#define T_COND_equals_path      39
#define T_COND_under_path      40
#define T_COND_paren      41
#define SEMI      42
#define COMMA      43
#define ASTERISK      44
#define DOT      45
#define PLUS      46
#define MINUS      47
#define DOUBLEVERTBAR      48
#define DIVIDE      49
#define EXPONENT      50
#define LPAREN      51
#define RPAREN      52
#define ARROW      53
#define FOUND_ATTR      54
#define NOTFOUND_ATTR      55
#define ISOPEN_ATTR      56
#define ROWCOUNT_ATTR      57
#define BULK_ROWCOUNT_ATTR      58
#define NUMBER      59
#define CHARSET_ATTR      60
#define ID      61
#define DOUBLEQUOTED_STRING      62
#define EQ      63
#define NOT_EQ      64
#define GTH      65
#define GEQ      66
#define LTH      67
#define LEQ      68
#define QUOTED_STRING      69
#define COLON      70
#define POINT      71
#define DOUBLEDOT      72
#define AT_SIGN      73
#define RBRACK      74
#define LBRACK      75
#define PERCENTAGE      76
#define LLABEL      77
#define RLABEL      78
#define ASSIGN      79
#define VERTBAR      80
#define NUM      81
#define QUOTE      82
#define WS      83
#define SL_COMMENT      84
#define ML_COMMENT      85
#define TYPE_ATTR      86
#define ROWTYPE_ATTR      87
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for YSmartLexer
 * =============================================================================
 */
/** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
